name: mesh
description: Fast and highly customizable animated Mesh Gradients for Flutter applications. Using Shaders and vertices.
version: 0.5.0
repository: https://github.com/renancaraujo/omesh/tree/main/flutter/mesh
issue_tracker: https://github.com/renancaraujo/omesh/issues
homepage: https://github.com/renancaraujo/omesh
documentation: https://github.com/renancaraujo/omesh/tree/main/flutter/mesh
topics: [mesh-gradients, flutter, shaders, mesh, gradient]
screenshots:
  - description: 'This screenshot shows a usage example of mesh gradients'
    path: doc/assets/preview.png

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  archive: ^4.0.6
  binarize: ^2.0.0
  cached_value: ^1.0.0
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
flutter:
  shaders:
    - shaders/omesh.frag
